version: '3.4'

services:
  delgado.server:
    image: ${DOCKER_REGISTRY-}delgadoserver
    build:
      context: .
      dockerfile: Delgado.Server/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDB__ConnectionString=mongodb://mongodb:27017
      - MongoDB__DatabaseName=mycv

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
